programa5_1: programa5_1.cpp PoligonoIrreg.o
	g++ programa5_1.cpp PoligonoIrreg.o Coordenada.o -o programa5_1
PoligonoIrreg.o: PoligonoIrreg.cpp Coordenada.o PoligonoIrreg.h
	g++ PoligonoIrreg.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c
